kind = "web"
previewPath = "/"
title = "Stellar NFT Minter"
version = "1.0.0"
id = "artifacts/stellar-nft-minter"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22441

[services.development]
run = "pnpm --filter @workspace/stellar-nft-minter run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/stellar-nft-minter", "run", "build" ]
publicDir = "artifacts/stellar-nft-minter/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22441"
BASE_PATH = "/"
